AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  cfmacro001function001:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./src
      Description: cloudformation macro
      MemorySize: 256
      Timeout: 10
  cfmacro001:
    Type: AWS::CloudFormation::Macro
    Properties: 
      Description: cloudformation macro 001
      FunctionName: !GetAtt cfmacro001function001.Arn
#      LogGroupName: String
#      LogRoleARN: String
      Name: cfmacro001